Menu dropdown
luis-pomare/Portfolio pull request #10
Opened 2022-01-25 19:39 UTC by luis-pomare

In this milestone, we have created the interactions of the main menu using DOM manipulation whit JS.

2022-01-25 20:01 UTC, MrBrN197 requested changes
## Hi,  @luis-pomare  👋  

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔The drop down menu functionality is working well

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-25 20:01 UTC, MrBrN197 commented on index.html
> +        </ul>
- [ ] Hi, The functionality of the dropdown menu is working perfectly. Although as part of the requirements you need to also ensure that the design matches the reference. Please make sure your design matches the Figma design.

Reference Design | Your Design
-|-
![image](https://user-images.githubusercontent.com/18730106/151050269-00ad2ce7-b994-44ef-8c22-2131025e7e8f.png)|![image](https://user-images.githubusercontent.com/18730106/151050309-e5efcb70-02c4-4ea9-b663-1dd3478554a9.png)

2022-01-26 03:19 UTC, mateo951 approved these changes
### Hi @luis-pomare, 

Awesome work making the changes requested by the previous reviewer 😁
Your project is complete!  There is nothing else to say other than... it's time to merge it 👌 

![](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 03:19 UTC, mateo951 commented on index.html
> +        </ul>
Addressed 🔥 Your popup is looking as expected 😎

2022-01-26 03:22 UTC, merged